### ISSUE TITLE
Drop down menu list for tables just stopped working

### ISSUE THREAD

**Issue by hodel33** [yy0931/sqlite3-editor#11]
Hi!
Hope all is well :)
Wanted to let you know that there's been some change in your SQLite3 Editor.
Out of nowhere today the drop down menu for tables (in place) just stopped working.
Could you please check into it? Love that functionality :)

Cheers!
Bjorn
![sqlite3_editor_drop_down_menu_in_place_disabled](https://user-images.githubusercontent.com/112579590/217849321-cf15dc73-da62-4625-9a8d-cc4ccae290fb.png)

**Comment by yy0931** [comment]
I wrote the reason for the change in # v1.0.53 in [changelog](https://marketplace.visualstudio.com/items/yy0931.vscode-sqlite3-editor/changelog) and the usage in the [README](https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor#switching-tables). I changed the UI because there was a performance issue when rendering many tables, but I also think the new UI is a bit less intuitive. Do you think it would be better to revert the change?

**Comment by hodel33** [comment]
Hi again :) Ahh I see. Uhm is there any chance of letting us users choose between the new one and old drop down? You could implement it in Options to the right? I'd love that. Have the new one as Default, and those who want, can easily change with the Option cog wheel :) ?

**Comment by yy0931** [comment]
Well, the new UI's UX is worse than I expected, so I'm going to make the drop-down the default and show a notification recommending the new UI when the number of tables is large.

**Comment by hodel33** [comment]
Ahh ok! Well that makes me very happy! Actually I fell in love with your extension mostly because of that drop down. Genius! So easy to use :) I've checked other SQL viewers, wasnt impressed at all. Yours is easily the best in terms of clean, easy to use, intuitive! Keep up the fantastic work :)

**Comment by yy0931** [comment]
I am happy to hear that. I've released v1.0.55 to revert the UI and add a configuration option.
