### ISSUE TITLE
Support the git-diff view

### ISSUE THREAD

**Issue by Wastus** [yy0931/sqlite3-editor#13]
If you have a SQLite database under version control, it would be nice to have support for the git-diff view like SQLite Viewer does.

Well the support there is quite limited, it just displays both versions, without any highlighting of the differences, but that's at least a start and I find it very helpful.

**Comment by yy0931** [comment]
Thank you for sharing your feedback.

Actually, VSCode's default behavior for custom editors in the diff view is to display both versions without highlighting the differences, but we intentionally display the error message `The sqlite3-editor extension doesn't support the git-diff view. Use the following command instead.` on top of it because I thought the default behavior is useless, so it is easy to support the feature. I'll do it by the next release.

To implement a proper diff support, we will need this feature request: https://github.com/microsoft/vscode/issues/138525.

**Comment by yy0931** [comment]
I have added support for diff editors in v1.0.68.
https://github.com/yy0931/sqlite3-editor/wiki/1.0.68

**Comment by Wastus** [comment]
Wow, this is even better than what I imagined. Great work. 👍
