### ISSUE TITLE
Maybe the tables list should be in the "Outline" section instead of its own

### ISSUE THREAD

**Issue by 9t8** [yy0931/sqlite3-editor#15]
IDK if there are technical limitations, but right now the "Outline" sidebar section is not being used and it would be nice if the table list was there instead of in its own section.

**Comment by yy0931** [comment]
That's a good suggestion, but it appears that the outline view is designed for text editors rather than custom editors. In order to support the outline view, [we would need to register a DocumentSymbolProvider](https://stackoverflow.com/a/57132237/10710682), but creating a [DocumentSymbol](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbol) requires a text range. Additionally, I couldn't find any information on how to add context menu to outline items.

**Comment by yy0931** [comment]
microsoft/vscode#97095 discusses adding support for CustomTextEditor (a custom editor for text data), but our extension uses CustomEditor (a custom editor for binary data) instead. Since I think moving the table list there offers limited benefits, I'm closing this issue now.
