### ISSUE TITLE
Loading does not finish when using Codespaces or code-server on iPad

### ISSUE THREAD

**Issue by root-lump** [yy0931/sqlite3-editor#37]
When I use this extension on `GitHub Codespaces`, `code-server`, etc., I can use it without any problems on my PC, but when I use it on my iPad, I have a problem loading the extension.

- **Safari or PWA**: I cannot use this extension unless I disable it and re-enable it after loading other extensions.
- **[Servediter](https://servediter.app/)**: Even if you disable only this extension and enable it again after loading other extensions, nothing is displayed.
In the case of GitHub Codespaces, it loads fine only on the first launch, but on subsequent launches it behaves similar to code-server + Safari.

_When there are loading problems, other extensions and Git-related VSCode features will be unavailable.
The same problem occurred even when testing with only this extension enabled._

I understand that it is used under minor circumstances, but I would appreciate it if you could address it.

**Comment by yy0931** [comment]
Thanks for the catch. I will try to reproduce it tomorrow.

**Comment by yy0931** [comment]
I was able to reproduce the issue and fixed it in v1.0.137.

It was due to a bug (or limitation) of codespaces, in which extensions with the activation event "onFileSystem:file" do not load. I used Firefox for reproduction because I was unable to get Safari on an old MacOS to load codespaces. If you find the bug still persists on Safari, please leave a comment.

**Comment by root-lump** [comment]
The problem is gone.
I love this extension! thank you!
