### ISSUE TITLE
Looks like the extension not available in market place for code-server

### ISSUE THREAD

**Issue by belonesox** [yy0931/sqlite3-editor#38]
Looks like the extension not available in market place for code-server:
![image](https://github.com/yy0931/sqlite3-editor/assets/1609739/ed178087-e38f-49bb-be29-e74c9d4681b3)

Declared as «Universal»:
![image](https://github.com/yy0931/sqlite3-editor/assets/1609739/9ea4cfd8-58fe-448c-b831-f60d05d8115a)

Tested on
```
code-server-4.18.0-1
code-server-4.19.1~rc.1-1
```

Am I do something wrong?

**Comment by yy0931** [comment]
You can't find it because code-server uses Open VSX (https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace) instead of Microsoft's Visual Studio Marketplace for downloading extensions, and the extension is not available on Open VSX. However, you can always manually download and install the extension from the Visual Studio Marketplace (https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor). Perhaps I'll consider uploading the extension to Open VSX.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/bd5f02f9-edcb-4ae6-bf68-47c63d34be17)

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/29fd8038-7b6c-4028-bf0a-ae49b39afdae)
