### ISSUE TITLE
Execution time for query

### ISSUE THREAD

**Issue by adopon** [yy0931/sqlite3-editor#62]
First of all spectacular extension. I know that project development slowed down as the following line in latest commit was removed "Feel free to report any issues or feature requests" was removed. I would kindly _(and not "freely")_ ask, is there  a way to implement execution time of query? Sometimes this would really help when optimizing new queries.

**Comment by yy0931** [comment]
Do you mean you want to check the duration it took to run a SQL query? If so, I remember I didn't implement that feature because it could be misleading;
1. The extension doesn't run the user's query as-is. It fetches only the visible rows when running a SELECT statement, but when fetching the first row was significantly slower than fetching subsequent rows, fetches more rows and caches them.
2. Also, because of SQLite' [caching](https://www.sqlite.org/pragma.html#pragma_cache_size), the first run of a query can sometimes be significantly slower than the second run.
